config/routes.rb
Rails.application.routes.draw do

  get "/meals/new" => "meals#new"
  post "/meals/new" => "groups#view"
  get "/meals/:id" => "groups#show", as: :group_meals
  post "/meals/:id" => "groups#show"
  get "/rpt_attend/" => "centers#rpt_attend"
  get "/rpt_meal/" => "centers#rpt_meal"

  resources :centers, only: [:show]
  resources :children, except: [:new]
  resources :groups
  resources :handoffs, only: [:create, :destroy]
  resources :meals, only: [:new, :create, :update, :destroy]
  resources :parents
  resources :teachers
  resources :families, only: [:new, :index, :create]

  root "home#index"

  get "/parent-log-in" => "sessions#new_parent", as: :parent_log_in

  post "/parent-log-in" => "sessions#create_parent"

  delete "/parent-log-out" => "sessions#destroy_parent", as: :parent_log_out

  get "/teacher-log-in" => "sessions#new_teacher", as: :teacher_log_in

  post "/teacher-log-in" => "sessions#create_teacher"

  delete "/teacher-log-out" => "sessions#destroy_teacher", as: :teacher_log_out

  get "/center-log-in" => "sessions#new_center", as: :center_log_in

  post "/center-log-in" => "sessions#create_center"

  delete "/center-log-out" => "sessions#destroy_center", as: :center_log_out

end

app/models/center.rb
class Center < ActiveRecord::Base
	has_many :teachers
	
	has_secure_password
    validates_confirmation_of :password
	validates_presence_of :password, on: :create
end

app/models/child.rb
class Child < ActiveRecord::Base
	has_many :meals
	has_many :handoffs
	belongs_to :group
	has_many :families
	has_many :parents, :through => :families
	validates_presence_of :fname, :lname, on: :create, presence: true
	
end

app/models/family.rb
# Family is a join table for child and parent.


class Family < ActiveRecord::Base
	belongs_to :child
	belongs_to :parent
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :children
	belongs_to :teacher
end

app/models/handoff.rb
class Handoff < ActiveRecord::Base
	belongs_to :child
end

app/models/meal.rb
class Meal < ActiveRecord::Base
	belongs_to :child
	belongs_to :teacher
end

app/models/parent.rb
class Parent < ActiveRecord::Base
	has_many :families
	has_many :children, through: :families
 
	has_secure_password
    validates_confirmation_of :password
	validates_presence_of :password, :name, :email, on: :create
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_one :group
	has_many :meals
	belongs_to :center

	has_secure_password
    validates_confirmation_of :password
	validates_presence_of :password, :email, :name, on: :create, presence: true
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  def index
    @children = Child.order("lname")
    @parent = Parent.order("name")
  end

  def show
    @child = Child.find(params[:id])
    @parents = Parent.all
  end

  def create
    @child = Child.new(child_params)
    if @child.save
      flash[:notice] = "Child #{@child.fname} #{@child.mname} #{@child.lname} is registered!"
    else
    flash[:alert] = "The child is not registered. First & last names are required."
    end
    redirect_to (:back)
  end

  def edit
    @child = Child.find(params[:id])
  end

  def update
    @child = Child.find(params[:id])
    if @child.update(child_params)
      flash[:notice] = "Child #{@child.fname} #{@child.lname} has been updated."
    else
      flash[:alert] = "Child #{@child.fname} #{@child.lname} did not update. Please try again."
    end
    redirect_to children_path, method: :get
  end

  def destroy
    if Child.find(params[:id]).destroy
      flash[:notice] = "The child was deleted."
    else
      flash[:alert] = "The child was not deleted. Please try again."
    end
    redirect_to children_path, method: :get
  end

  private

   def child_params
    params.require(:child).permit(:fname, :mname, :lname, :food_subsidy, :group_id)
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def new
      @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
      if @meal.save
        # redirect_to group_meals_path(Child.find(params[:meal][:child_id]).group)
        flash[:notice] = "Meals were saved."
      else
        flash[:alert] = "There was a problem recording the meals. Please try again."
    end
    redirect_to (:back)
  end

  def update
    @meal = Meal.find(params[:id])
    if @meal.update(meal_params)
      flash[:notice] = "Meals were updated."
    else
      flash[:alert] = "Meals were not updated; try again."
    end
    redirect_to (:back)
  end

  def destroy
    Meal.find(params[:id]).destroy
    redirect_to (:back)
  end

  private

  def meal_params
    params.require(:meal).permit(:child_id, :signature, :meal_type, :teacher_id, :meal_date, :breakfast, :am_snack, :lunch, :pm_snack, :supper, :late_snack)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/handoffs_helper.rb
module HandoffsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
# Logs in the parent.
	def parent_log_in(parent)
		session[:parent_id] = parent.id
	end

# Returns the currentlogged-in parent (if any).
	def current_parent
		@current_parent ||= Parent.find_by(id: session[:parent_id])
	end

# Returns true if the user is logged in, false otherwise.
	def parent_logged_in?
		!current_parent.nil?
	end
# Logs in the teacher.
	def teacher_log_in(teacher)
		session[:teacher_id] = teacher.id
	end

# Returns the current logged-in teacher (if any).
	def current_teacher
		@current_teacher ||= Teacher.find_by(id: session[:teacher_id])
	end

# Returns true if the teacher is logged in, false otherwise.
	def teacher_logged_in?
		!current_teacher.nil?
	end	

# Logs in the center.
	def center_log_in(center)
		session[:center_id] = center.id
	end

# Returns the current logged-in center (if any).
	def current_center
		@current_center ||= Center.find_by(id: session[:center_id])
	end

# Returns true if the center is logged in, false otherwise.
	def center_logged_in?
		!current_center.nil?
	end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/children/edit.html.erb
<!-- Edit action form for child update or delete  -->

<div id="teacher_edit" class="title_center">
	<h3> Child Update/Delete <h3>
</div><br>

<div id="teacher_update" class="sign_up">
		<%= form_for @child do |f| %> 
		
		<%= f.text_field :fname, placeholder:"child first name"   %><br><br>
		
		<%= f.text_field :mname, placeholder:"child middle name"   %><br><br>
		
		<%= f.text_field :lname, placeholder:"child last name"  %><br><br>
		<%= f.label :Meal_Subsidy %>
		<%= f.select :food_subsidy, ['None', 'Free', 'Reducted'] %><br><br>
		<%= f.label :Class_Select %>
		<%= f.collection_select :group_id, Group.all, :id, :name, include_blank: true %><br><br>
		<%= f.submit "Update Child", :class => 'f_submit' %>
		<% end %>
		<br>
	<%= button_to "Delete Child", child_path(@child.id), class: 'button_c', method: :delete %>
	<br>
	<%= button_to "Center Home", center_path(current_center), class: 'button_c', method: :get %>
	</div>
</div>

app/views/children/index.html.erb
<!-- List all children and parents to select child or parent prior to update/delete page -->

<div class="title_center">
		<h3>Select Family Member</h3> 
		<h5>-&nbspchildren&nbsp-&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp-&nbspparents&nbsp-</h5>
</div>

<div class="child_index">
	<div class="reports_family">
		<% @children.each do |child| %>
			<a href="<%= edit_child_path(child.id) %>">
			<h3><%= child.fname %>
				<%= child.mname %>
				<%= child.lname %></h3>
			</a>
		<% end %>
	</div>
	<div class="reports_family">
		<% @parent.each do |parent| %>
			<a href="<%= edit_parent_path(parent.id) %>">
			<h3><%= parent.name %></h3>
			</a>
		<% end %>
	</div>
</div>
<div class="button_adjust">	
		<%= button_to "Center Home", center_path(current_center), class: 'button_c', method: :get %>
</div>

app/views/children/show.html.erb
<!-- The admin selects the child's parent which enters the parent_id and child_id into the family join table. -->

<div id="attach_parent">

<!-- If child has no parents in the db yet, "Registered parents for..." is not displayed. -->
	<br>
	<% if @child.parents.length != 0 %>
		<h3> Registered Parents for 
		<%= @child.fname %> 
		<%= @child.mname %> 
		<%= @child.lname %>:</h3>
	<% end %>

	<% @child.parents.each do |parent| %>
		<%= parent.name %><br>
	<% end %>
	<br>

	<h1> <%= "Add a parent to" %> <%= @child.fname %><%= "'s family." %> </h1>

	<%= form_for Family.new do |f| %>
		<%= f.hidden_field :child_id, :value => @child.id %>
		<%= f.collection_select :parent_id, @parents, :id, :name, prompt: false %>
		<%= f.submit "Select a Parent", :class => 'f_submit'  %>
	<% end %><br><br><br><br><br>
	
	<div id="child_show" class="center_div">
		<%= button_to "Center Home", center_path(current_center), class: 'button_c', method: :get %>
	</div>
</div>