config/routes.rb
Rails.application.routes.draw do

  get "/meals/new" => "meals#new"
  post "/meals/new" => "groups#view"
  get "/meals/:id" => "groups#show", as: :group_meals
  post "/meals/:id" => "groups#show"
  get "/rpt_attend/" => "centers#rpt_attend"
  get "/rpt_meal/" => "centers#rpt_meal"

  resources :centers, only: [:show]
  resources :children, except: [:new]
  resources :groups
  resources :handoffs, only: [:create, :destroy]
  resources :meals, only: [:new, :create, :update, :destroy]
  resources :parents
  resources :teachers
  resources :families, only: [:new, :index, :create]

  root "home#index"

  get "/parent-log-in" => "sessions#new_parent", as: :parent_log_in

  post "/parent-log-in" => "sessions#create_parent"

  delete "/parent-log-out" => "sessions#destroy_parent", as: :parent_log_out

  get "/teacher-log-in" => "sessions#new_teacher", as: :teacher_log_in

  post "/teacher-log-in" => "sessions#create_teacher"

  delete "/teacher-log-out" => "sessions#destroy_teacher", as: :teacher_log_out

  get "/center-log-in" => "sessions#new_center", as: :center_log_in

  post "/center-log-in" => "sessions#create_center"

  delete "/center-log-out" => "sessions#destroy_center", as: :center_log_out

end

app/models/center.rb
class Center < ActiveRecord::Base
	has_many :teachers
	
	has_secure_password
    validates_confirmation_of :password
	validates_presence_of :password, on: :create
end

app/models/child.rb
class Child < ActiveRecord::Base
	has_many :meals
	has_many :handoffs
	belongs_to :group
	has_many :families
	has_many :parents, :through => :families
	validates_presence_of :fname, :lname, on: :create, presence: true
	
end

app/models/family.rb
# Family is a join table for child and parent.


class Family < ActiveRecord::Base
	belongs_to :child
	belongs_to :parent
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :children
	belongs_to :teacher
end

app/models/handoff.rb
class Handoff < ActiveRecord::Base
	belongs_to :child
end

app/models/meal.rb
class Meal < ActiveRecord::Base
	belongs_to :child
	belongs_to :teacher
end

app/models/parent.rb
class Parent < ActiveRecord::Base
	has_many :families
	has_many :children, through: :families
 
	has_secure_password
    validates_confirmation_of :password
	validates_presence_of :password, :name, :email, on: :create
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_one :group
	has_many :meals
	belongs_to :center

	has_secure_password
    validates_confirmation_of :password
	validates_presence_of :password, :email, :name, on: :create, presence: true
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController

  def new
    @family = Family.new
  end

  def create
    @family = Family.new(family_params)
    if @family.save
      flash[:notice] = "Parent and child are now connected!"
      redirect_to families_path
    else
      flash[:alert] = "The parent-child connection failed. Please try again."
      redirect_to (:back)
    end
  end

  def index
    @children = Child.order("lname")
  end

  private

  def family_params
    params.require(:family).permit(:child_id, :parent_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.order("name")
  end

# detecting no group select error before system abbend.
  def view
    if params[:group][:id] == ""
      flash[:alert] = "First select your class."
      redirect_to (:back)
    else  
      redirect_to group_path(params[:group][:id])
    end
  end

  def show
    @teacher = current_teacher
  # accounting for nested or unnested params
    if params[:group] && params[:group][:id]
      @group = Group.find(params[:group][:id])
    else 
      @group = Group.find(params[:id])
    end
  #
    if params[:date]
      @date = DateTime.new(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i)
    else
      @date = DateTime.now.to_date
    end
  end

  def new
    @group = Group.new
    @teachers = Teacher.all
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "Class #{@group.name} is registered!"
      redirect_to (:back)
    else
      flash[:alert] = "There was a problem registering a new class. Please try again."
      redirect_to (:back)
    end
  end

  def edit
    @group = Group.find(params[:id])
    @teachers = Teacher.order("name")
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:notice] = "Class #{@group.name} was updated."
      redirect_to groups_path, method: :get
    else
      flash[:alert] = "Class update failed. Please try again."
      redirect_to (:back)
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.destroy
      flash[:notice] = "The class was deleted."
      redirect_to groups_path, method: :get
    else
      flash[:alert] = "The class did not delete. Please try again."
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :teacher_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def new
      @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
      if @meal.save
        # redirect_to group_meals_path(Child.find(params[:meal][:child_id]).group)
        flash[:notice] = "Meals were saved."
      else
        flash[:alert] = "There was a problem recording the meals. Please try again."
    end
    redirect_to (:back)
  end

  def update
    @meal = Meal.find(params[:id])
    if @meal.update(meal_params)
      flash[:notice] = "Meals were updated."
    else
      flash[:alert] = "Meals were not updated; try again."
    end
    redirect_to (:back)
  end

  def destroy
    Meal.find(params[:id]).destroy
    redirect_to (:back)
  end

  private

  def meal_params
    params.require(:meal).permit(:child_id, :signature, :meal_type, :teacher_id, :meal_date, :breakfast, :am_snack, :lunch, :pm_snack, :supper, :late_snack)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/handoffs_helper.rb
module HandoffsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
# Logs in the parent.
	def parent_log_in(parent)
		session[:parent_id] = parent.id
	end

# Returns the currentlogged-in parent (if any).
	def current_parent
		@current_parent ||= Parent.find_by(id: session[:parent_id])
	end

# Returns true if the user is logged in, false otherwise.
	def parent_logged_in?
		!current_parent.nil?
	end
# Logs in the teacher.
	def teacher_log_in(teacher)
		session[:teacher_id] = teacher.id
	end

# Returns the current logged-in teacher (if any).
	def current_teacher
		@current_teacher ||= Teacher.find_by(id: session[:teacher_id])
	end

# Returns true if the teacher is logged in, false otherwise.
	def teacher_logged_in?
		!current_teacher.nil?
	end	

# Logs in the center.
	def center_log_in(center)
		session[:center_id] = center.id
	end

# Returns the current logged-in center (if any).
	def current_center
		@current_center ||= Center.find_by(id: session[:center_id])
	end

# Returns true if the center is logged in, false otherwise.
	def center_logged_in?
		!current_center.nil?
	end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/families/index.html.erb
<!-- To create a family, the admin chooses a child from this list which links the admin to the family creation page. -->

<div class="title_center">
	<h2>Select Child</h2> 
</div>
	
<div class="reports">
	<% @children.each do |child| %>

		<a href="<%= child_path(child.id) %>">
		<h3><%= child.fname %>
			<%= child.mname %>
			<%= child.lname %></h3>
		</a>

	<% end %>
</div>
<br><br>
<div id="family_button" class="center_div">
	<%= button_to "Center Home", center_path(current_center), class: 'button_c', method: :get %>
</div>

app/views/families/new.html.erb
<div class="title_center">
	<h2> Family <h2>
</div>

<!-- Form for registering a new parent. -->

<div class="family_forms">
	<div class="parent_child">
		<%= form_for Parent.new do |f| %>
		
		<%= f.text_field :name, placeholder:"parent name"  %><br><br>
		<%= f.text_field :email, placeholder:"parent email"   %><br><br>
		<%= f.password_field :password, placeholder:"parent password"   %><br><br>
		<%= f.submit "Register Parent", :class => 'f_submit' %>
		<% end %>
	</div>

<!-- Form for registering a new child. -->

	<div class="parent_child">
		<%= form_for Child.new do |f| %> 
		
		<%= f.text_field :fname, placeholder:"child first name"   %><br><br>
		
		<%= f.text_field :mname, placeholder:"child middle name"   %><br><br>
		
		<%= f.text_field :lname, placeholder:"child last name"  %><br><br>
		<%= f.label :Meal_Subsidy %>
		<%= f.select :food_subsidy, ['None', 'Free', 'Reducted'] %><br><br>
		<%= f.label :Class_Select %>
		<%= f.collection_select :group_id, Group.all, :id, :name, prompt: false %><br><br>
		<%= f.submit "Register Child", :class => 'f_submit' %>
		<% end %><br>
	</div>
</div>

<div class="family_div">
	<div class="left_button">
		<%= button_to "Make Family", families_path, class: 'button_c', method: :get %>
	</div>
	<div id="middle_button">
		<%= button_to "Edit/Delete Family", children_path, class: 'button_c', method: :get %>
	</div>
	<div class="right_button">	
		<%= button_to "Center Home", center_path(current_center), class: 'button_c', method: :get %>
	</div>
	
</div>