config/routes.rb
Rails.application.routes.draw do

  get "/meals/new" => "meals#new"
  post "/meals/new" => "groups#view"
  get "/meals/:id" => "groups#show", as: :group_meals
  post "/meals/:id" => "groups#show"
  get "/rpt_attend/" => "centers#rpt_attend"
  get "/rpt_meal/" => "centers#rpt_meal"

  resources :centers, only: [:show]
  resources :children, except: [:new]
  resources :groups
  resources :handoffs, only: [:create, :destroy]
  resources :meals, only: [:new, :create, :update, :destroy]
  resources :parents
  resources :teachers
  resources :families, only: [:new, :index, :create]

  root "home#index"

  get "/parent-log-in" => "sessions#new_parent", as: :parent_log_in

  post "/parent-log-in" => "sessions#create_parent"

  delete "/parent-log-out" => "sessions#destroy_parent", as: :parent_log_out

  get "/teacher-log-in" => "sessions#new_teacher", as: :teacher_log_in

  post "/teacher-log-in" => "sessions#create_teacher"

  delete "/teacher-log-out" => "sessions#destroy_teacher", as: :teacher_log_out

  get "/center-log-in" => "sessions#new_center", as: :center_log_in

  post "/center-log-in" => "sessions#create_center"

  delete "/center-log-out" => "sessions#destroy_center", as: :center_log_out

end

app/models/center.rb
class Center < ActiveRecord::Base
	has_many :teachers
	
	has_secure_password
    validates_confirmation_of :password
	validates_presence_of :password, on: :create
end

app/models/child.rb
class Child < ActiveRecord::Base
	has_many :meals
	has_many :handoffs
	belongs_to :group
	has_many :families
	has_many :parents, :through => :families
	validates_presence_of :fname, :lname, on: :create, presence: true
	
end

app/models/family.rb
# Family is a join table for child and parent.


class Family < ActiveRecord::Base
	belongs_to :child
	belongs_to :parent
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :children
	belongs_to :teacher
end

app/models/handoff.rb
class Handoff < ActiveRecord::Base
	belongs_to :child
end

app/models/meal.rb
class Meal < ActiveRecord::Base
	belongs_to :child
	belongs_to :teacher
end

app/models/parent.rb
class Parent < ActiveRecord::Base
	has_many :families
	has_many :children, through: :families
 
	has_secure_password
    validates_confirmation_of :password
	validates_presence_of :password, :name, :email, on: :create
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_one :group
	has_many :meals
	belongs_to :center

	has_secure_password
    validates_confirmation_of :password
	validates_presence_of :password, :email, :name, on: :create, presence: true
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController

  def rpt_attend
    @children = Child.order("lname")
  end

   def rpt_meal
    @children = Child.order("lname")
  end

  def show
    @center = Center.find(params[:id])
     if @center != current_center
      flash[:alert] = "You do not have access to this page."
      redirect_to root_path
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.order("name")
  end

# detecting no group select error before system abbend.
  def view
    if params[:group][:id] == ""
      flash[:alert] = "First select your class."
      redirect_to (:back)
    else  
      redirect_to group_path(params[:group][:id])
    end
  end

  def show
    @teacher = current_teacher
  # accounting for nested or unnested params
    if params[:group] && params[:group][:id]
      @group = Group.find(params[:group][:id])
    else 
      @group = Group.find(params[:id])
    end
  #
    if params[:date]
      @date = DateTime.new(params[:date][:year].to_i, params[:date][:month].to_i, params[:date][:day].to_i)
    else
      @date = DateTime.now.to_date
    end
  end

  def new
    @group = Group.new
    @teachers = Teacher.all
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "Class #{@group.name} is registered!"
      redirect_to (:back)
    else
      flash[:alert] = "There was a problem registering a new class. Please try again."
      redirect_to (:back)
    end
  end

  def edit
    @group = Group.find(params[:id])
    @teachers = Teacher.order("name")
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:notice] = "Class #{@group.name} was updated."
      redirect_to groups_path, method: :get
    else
      flash[:alert] = "Class update failed. Please try again."
      redirect_to (:back)
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.destroy
      flash[:notice] = "The class was deleted."
      redirect_to groups_path, method: :get
    else
      flash[:alert] = "The class did not delete. Please try again."
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :teacher_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def new
      @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
      if @meal.save
        # redirect_to group_meals_path(Child.find(params[:meal][:child_id]).group)
        flash[:notice] = "Meals were saved."
      else
        flash[:alert] = "There was a problem recording the meals. Please try again."
    end
    redirect_to (:back)
  end

  def update
    @meal = Meal.find(params[:id])
    if @meal.update(meal_params)
      flash[:notice] = "Meals were updated."
    else
      flash[:alert] = "Meals were not updated; try again."
    end
    redirect_to (:back)
  end

  def destroy
    Meal.find(params[:id]).destroy
    redirect_to (:back)
  end

  private

  def meal_params
    params.require(:meal).permit(:child_id, :signature, :meal_type, :teacher_id, :meal_date, :breakfast, :am_snack, :lunch, :pm_snack, :supper, :late_snack)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/handoffs_helper.rb
module HandoffsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
# Logs in the parent.
	def parent_log_in(parent)
		session[:parent_id] = parent.id
	end

# Returns the currentlogged-in parent (if any).
	def current_parent
		@current_parent ||= Parent.find_by(id: session[:parent_id])
	end

# Returns true if the user is logged in, false otherwise.
	def parent_logged_in?
		!current_parent.nil?
	end
# Logs in the teacher.
	def teacher_log_in(teacher)
		session[:teacher_id] = teacher.id
	end

# Returns the current logged-in teacher (if any).
	def current_teacher
		@current_teacher ||= Teacher.find_by(id: session[:teacher_id])
	end

# Returns true if the teacher is logged in, false otherwise.
	def teacher_logged_in?
		!current_teacher.nil?
	end	

# Logs in the center.
	def center_log_in(center)
		session[:center_id] = center.id
	end

# Returns the current logged-in center (if any).
	def current_center
		@current_center ||= Center.find_by(id: session[:center_id])
	end

# Returns true if the center is logged in, false otherwise.
	def center_logged_in?
		!current_center.nil?
	end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/centers/rpt_attend.html.erb
<!-- Report lists all handoffs (pickups and dropoffs) for each child. The child is dropped from the report if no handoffs are on record. -->

<% Time.zone = 'America/New_York' %>
<div class="title_center"> 
	<h2> Attendance </h2>
</div>
<br>
<div class="reports">

	<% @children.each do |child| %>
		 <% if child.handoffs.length != 0 %>
			<div id="attend_rpt">
			<%= child.fname %>
			<%= child.mname %>
			<%= child.lname %>
			</div>
			<br>
			<% child.handoffs.each do |handoff| %>
				<%= handoff.attend %>
				<%= ":" %>
				<%= handoff.created_at.strftime("%d %b. %Y - %H:%M")  %><br>
			<% end %>
		    <br>
		 <% end %>
	<% end %>
</div>
<br><br>
<div class="center_div">
	<%= button_to "Center Home", center_path(current_center), class: 'button_c', method: :get %>
</div>

app/views/centers/rpt_meal.html.erb
<!-- This report counts the number of meals for each child by meal type.  The child is dropped from the report if no meals on record. -->

<div class="title_center"> 
	<h2> Meal Counts by Child </h2>
</div>
<br>
<div class="reports">
	<% @children.each do |child| %>

	<% @breakfast = 0 %>
	<% @am_snack = 0 %>
	<% @lunch = 0 %>
	<% @pm_snack = 0 %>
	<% @supper = 0 %>
	<% @late_snack = 0 %>
	<% @total_meals = 0 %>
		<% child.meals.each do |meal| %>
			<% if meal.breakfast %>
				<% @breakfast += 1 %>
				<% @total_meals += 1 %>
			<% end %>
			<% if meal.am_snack %>
				<% @am_snack += 1 %>
				<% @total_meals += 1 %>
			<% end %>
			<% if meal.lunch %>
				<% @lunch += 1 %>
				<% @total_meals += 1 %>
			<% end %>
			<% if meal.pm_snack %>
				<% @pm_snack += 1 %>
				<% @total_meals += 1 %>
			<% end %>
			<% if meal.supper %>
				<% @supper += 1 %>
				<% @total_meals += 1 %>
			<% end %>
			<% if meal.late_snack %>
				<% @late_snack += 1 %>
				<% @total_meals += 1 %>
			<% end %>
		<% end %>

		<% if @total_meals != 0 %>
			<h3>
			<%= child.fname %>
			<%= child.mname %>
			<%= child.lname %>
			</h3>
			<%= "Breakfast:" %> 
			<%= @breakfast %>
			<%= "AM Snack:" %>
			<%= @am_snack %>
			<%= "Lunch:" %>
			<%= @lunch %>
			<%= "PM Snack:" %>
			<%= @pm_snack %>
			<%= "Supper:" %>
			<%= @supper %>
			<%= "Late Snack:" %>
			<%= @late_snack %>
			<br>
		<% end %>
	<% end %>
</div>
<br><br>
<div id="meals_rpt_button" class="center_div">
	<%= button_to "Center Home", center_path(current_center), class: "button_c", method: :get %>
</div>

app/views/centers/show.html.erb
<!-- This is the landing/home page for the center admin. -->

<div id="center_show">
	 <% if flash[:alert] %>
	    	<div class="notice"><%= flash[:alert] %></div>
	 <% end %>
	<div id="center_show2">
		 <h1><%= "#{@center.name}" %></h1> 
		<h2 id="sub_title"> Administration </h2>
		<h2 class="red"> Reports </h2>
			<strong class="font_size"><%= link_to "Meals", rpt_meal_path %><br></strong>
			<strong class="font_size"><%= link_to "Attendance", rpt_attend_path %></strong><br>
		<h2 class="red"> People </h2>
			<strong class="font_size"><%= link_to "Family", new_family_path %></strong>
			<strong class="font_size"><%= link_to "- Teacher -", new_teacher_path %></strong>
			<strong class="font_size"><%= link_to "Class", new_group_path %></strong>

		<!-- <h3> sign up, update, delete </h3> -->
		<br><br>
		<%= button_to "Logout", center_log_out_path, class: 'button_c', method: :delete %>
	</div>
</div>

app/views/groups/edit.html.erb
<!-- Admin can update or delete a class (group) from this page. -->
<br>
<div id="group_title" class="title_center">
	<h3> Class Update/Delete <h3>
</div>

<div  id="group_align" class="sign_up">
<br><br>
	<%= form_for @group do |f| %>
			<%= f.label :change_class_name %><br>
			<%= f.text_field :name %><br><br>
			<%= f.label :change_teacher %><br>
			<%= f.collection_select :teacher_id, @teachers, :id, :name, include_blank: true %><br><br>
			
			<%= f.submit "Submit Changes", :class => 'f_submit'  %>
	<% end %>
	<br><br>
	<%= button_to "Delete Class", group_path(@group.id), class: 'button_c', method: :delete %>
	<br>
	<%= button_to "Center Home", center_path(current_center), class: 'button_c', method: :get %>
	</div>
</div>

		
        

app/views/groups/index.html.erb
<!-- Admin can select a class (group) from this list in order to update or delete the class. -->

<div class="title_center">
	<H3> Select a Class </H3>
</div>

<div class="reports">
	<% @groups.each do |group| %>
		<a href="<%= edit_group_path(group.id) %>"><h3><%= group.name %></h3></a>
	<% end %>
	<br>
</div>
<br>
<div  id="group_button" class="center_div">
		<%= button_to "Center Home", center_path(current_center), class: 'button_c', method: :get %>
</div>

app/views/groups/new.html.erb
<div class="sign_up">
<br>
	<h1>Make New Class</h1>

	<%= form_for Group.new do |f| %>

			<%= f.label :Class_Name %><br>
			<%= f.text_field :name %><br><br>
			<%= f.label :Select_Teacher %><br>
			<%= f.collection_select :teacher_id, @teachers, :id, :name, prompt: false %>
			<br><br>
			<%=f.submit "Make Class", :class => 'f_submit'  %>
			<br>
	<%end%>
	<br><br>
	<%= button_to "Edit/Delete Class", groups_path, class: 'button_c', method: :get %>
	<br>
	<%= button_to "Center Home", center_path(current_center), class: 'button_c', method: :get %>
</div>

app/views/groups/show.html.erb
<!-- A teacher uses this page to account for each meal the child has on any day. New meal records can be created and updated using the same form on this one page. -->

<div id="meal_form">
	<h1> Meals for class: <%= @group.name %> </h1>

	<%= form_tag group_meals_path(@group) do %>
		<%= select_date(date = @date, options = {}, html_options = {}) %>
		<%= submit_tag "Select Meals Date" %>
	<% end %>
	<br>
</div>
<div class="reports_meals">
	<% if @group.children.length == 0 %>
		<i> (There are no children registered for this class.) </i>
	<% end %>
	<% @group.children.each do |child| %>
		
<!-- If a meal record for the selected date already exists, then do an update, if not, then create a new meal. -->

		<br>
		<% if child.meals.where(meal_date: @date).first %>
			<% @meal = child.meals.where(meal_date: @date).first %>
		<% else %>
			<% @meal = Meal.new %>
		<% end %>

		<%= form_for @meal do |f| %>
		<%= f.hidden_field :meal_date, value: @date %>
			<div id="child_bold">
				<%= child.fname %>
				<!-- <%= child.mname %> -->
				<%= child.lname %>
			</div>
			
			<strong>
			<%= f.check_box(:breakfast)%>
			<%= label_tag(:breakfast, "breakfast") %>

			<%= f.check_box(:am_snack) %>
			<%= label_tag(:am_snack, "am snack") %>

			<%= f.check_box(:lunch) %>
			<%= label_tag(:lunch, "lunch") %>

			<%= f.check_box(:pm_snack) %>
			<%= label_tag(:pm_snack, "pm snack") %>

			<%= f.check_box(:supper) %>
			<%= label_tag(:supper, "supper") %>

			<%= f.check_box(:late_snack) %>
			<%= label_tag(:late_snack, "late snack") %>

			<%= f.hidden_field :teacher_id, :value => @teacher.id %>
			<%= f.hidden_field :child_id, :value => child.id %>
			<%= f.button :submit, class: 'f_submit' %>
			</strong>
			<br>
		<% end %>
	<% end %>
</div><br>

<div class="center_div">
	<%= button_to "Logout", teacher_log_out_path, class: 'button_t', method: :delete %>
</div>

app/views/meals/new.html.erb
<!-- Teacher selects their class before meal accounting. -->


<div id="meals_group">
	
	<h1>Meals Accounting</h1>
	
	
	<div id="group_select">
		<h2>Select Class</h2>
		<%= form_tag do %>
		 	<%= collection_select(:group, :id, Group.all, :id, :name, :prompt => false) %>
		 	<%= button_to "submit class", :class => 'f_submit' %>
		<% end %>
	</div>
 </div>